import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import NavigationTransitionProvider from "@provider/NavigationTransitionProvider";
import Link from "next/link";

const mono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={mono.className}>
        <header className="flex items-center gap-2">
          <Link className="btn" href={"/"}>Home</Link>
          <Link className="btn" href={"/about"}>About</Link>
        </header>
        <NavigationTransitionProvider>
          {children}
        </NavigationTransitionProvider>
      </body>
    </html>
  );
}
